создана ветка спринта 6
SelyukSergey/MovieQuiz pull request #3
Opened 2024-12-23 14:27 UTC by SelyukSergey

2024-12-24 18:42 UTC, protos17 requested changes

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
Рекомендую указать как `private`

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = true // скрываем индикатор загрузки
Рекомендую использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) 
у activityIndicator вместо ручного управления свойством isHidden. 
Когда ты будешь вызывать startAnimating – индикатор будет появляться, а при stopAnimating – прятаться, а свойство isHidden уже не понадобится, индикатор все сделает за тебя. 
Эту настройку делают всего раз раз: кодом во viewDidLoad или галочкой на сториборде.

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +    //    ]
Знаю что в учебнике рекомендовано оставлять мок-вопросы, но рекомендую их удалить, потому что они больше не будут нужны

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didLoadDataFromServer()
Обращу внимание на свойство `errorMessage`. 
Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. 
С пустым списком приложение будет выглядеть сломанным. 
Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, 
эту ошибку разработчики должны были вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). 
Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. 
Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).
 **Примеры состояний, когда такое происходит:**
- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера(картинка). 
Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.
В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. 
В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно, ведь изображения нет.
Это состояние стоит обработать, например, с помощью алерта. 
Не забудь, что алерт будет обновлять UI и это тоже нужно учесть (вернуть на main), ровно также, как и прерывание функции (сделать return)

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = "Рейтинг этого фильма больше чем 7?"
Если чувствуешь в себе силы, можешь попробовать реализовать поддержку различных вопросов больше и меньше

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    var questionFactory: QuestionFactoryProtocol?
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления.

2024-12-24 18:42 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)
Приложение не отображает вопросы, потому что ты создаешь здесь QuestionFactory, но после завершения метода `viewDidLoad` этот класс не сохраняется. Чтобы это исправить, необходимо присвоить этот класс в переменную в области видимости класса:

    questionFactory = QuestionFactory(moviesLoader: MoviesLoader(), delegate: self)

2025-01-07 17:42 UTC, So1ovyov commented on MovieQuiz/Presentation/AlertPresenter.swift
>  class AlertPresenter {
Давай добавим модификатор `final` для этого класса. Он необходим для оптимизации проекта, также не позволит наследоваться от данного класса.

2025-01-07 17:42 UTC, So1ovyov commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.hidesWhenStopped = true // настраиваем индикатор на автоматическое скрытие при остановке анимации
В целом понятно для чего эта строка, комментарий можно удалить.

2025-01-07 17:42 UTC, So1ovyov commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>      private var currentQuestionIndex: Int = 0
В языке `swift` много синтаксического сахара, например можно использовать конструкцию `.zero`
```
private var currentQuestionIndex: Int = .zero
private var correctAnswers: Int = .zero
```
Это опцониально, в случае если тебе понравится такой стиль.

2025-01-07 17:43 UTC, So1ovyov commented on MovieQuiz/Services/QuestionFactory.swift
>  class QuestionFactory: QuestionFactoryProtocol {
Проверь во всех классах наличие модификатора `final`, он не нужен только если ты планируешь наследоваться от класса

2025-01-07 17:44 UTC, So1ovyov commented on MovieQuiz/Services/QuestionFactory.swift
> +                let text = "Рейтинг этого фильма больше чем 7?"
Если будет желание, предлагаю добавить в логику генерации вопроса больше/меньше и рейтинг от 1 до 9

2025-01-07 17:44 UTC, So1ovyov commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.global().async { [weak self] in
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2025-01-07 17:47 UTC, So1ovyov commented
@SelyukSergey отличная работа, успехов в следующем спринте!

2025-01-09 08:05 UTC, merged